### ISSUE TITLE
split loadtest.py into "CRUD"-like modules

### ISSUE THREAD

**Issue by rpappalax** [mozilla-services/screenshots-loadtests#16]
loadtest_read.py (for read, search, list)
- global_setup:  login, create 100 users

loadtest_create.py (for create)
- global_setup:  login

loadtest_delete.py (delete_logins)
- setup: login, create 100 users

**Comment by pdehaan** [comment]
![img_0467](https://cloud.githubusercontent.com/assets/557895/23818130/4a86a322-05ad-11e7-87ef-93b9800afe3a.jpg)

**Comment by pdehaan** [comment]
This is blocked because we cannot upload any images in a `@global_setup` or `@setup` due to the fact that you need to be logged in to perform a `create_shot()` action. Currently both the `@global_setup` and `@setup` methods are used to create the `session` object that are used by the scenarios.

Not sure how we can write/maintain a synchronous (for setup) and asynchronous (for scenarios) versions of these methods.
We _could_ write a synchronous version of `create_shot()` for our `read_shot` scenario, but then we'll also need to rewrite all the login/register functionality as well. 

We _could_ just point the `read_shot` scenario to an existing image on stage (since a user doesn't need to be logged in to **view** a shot, but that doesn't help us with the list_shots and search_shots scenarios, where a user will need to have X existing shots and be logged in to run the tests.

**Comment by pdehaan** [comment]
I think we're CRUDdy enough to close this.
